server:
  http_listen_port: 9080
  grpc_listen_port: 0
  http_listen_address: 0.0.0.0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    tenant_id: "perplexica"
    batchwait: 1s
    batchsize: 102400
    backoff_config:
      min_period: 100ms
      max_period: 5s
      max_retries: 10
    timeout: 10s
    follow_redirects: true

scrape_configs:
  - job_name: system
    pipeline_stages:
      - json:
          expressions:
            timestamp: time
            level: level
            message: msg
    static_configs:
      - targets:
          - 0.0.0.0
        labels:
          job: perplexica
          __path__: /var/log/*.log

  - job_name: docker
    pipeline_stages:
      - json:
          expressions:
            timestamp: time
            level: level
            message: msg
    static_configs:
      - targets:
          - 0.0.0.0
        labels:
          job: docker
          __path__: /var/log/docker/*.log

  - job_name: containers
    pipeline_stages:
      - json:
          expressions:
            timestamp: time
            level: level
            message: msg
    static_configs:
      - targets:
          - 0.0.0.0
        labels:
          job: containers
          __path__: /var/log/containers/*.log 